source 'https://gems.ruby-china.com'
# source 'https://rubygems.org'

gem 'nokogiri'

# https://github.com/bkeepers/dotenv
# gem 'dotenv-rails', groups: [:development, :test]
gem 'dotenv'

# iruby related
# https://github.com/SciRuby/iruby
# gem 'iruby'
gem 'pry'

# https://github.com/mrkn/pycall.rb
gem 'pycall'
gem 'pandas'
gem 'numpy'
gem 'matplotlib'
